HW11 done
Torchun/otus-go pull request #11
Opened 2024-01-16 16:25 UTC by Torchun

## Домашнее задание №11 «Клиент TELNET»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 2 баллов
- [ ] Понятность и чистота кода - до 4 баллов

#### Зачёт от 7 баллов

2024-01-16 16:31 UTC, Torchun commented
Локально тесты проходят:
```
$ ./test.sh 
+ go build -o go-telnet
+ NC_PID=898095
+ sleep 1
+ echo -e 'Hello\nFrom\nNC\n'
+ cat
+ nc -l localhost 4242
+ TL_PID=898099
+ echo -e 'I\nam\nTELNET client\n'
+ sleep 5
+ cat
+ ./go-telnet --timeout=5s localhost 4242
2024/01/16 19:29:41 connected to  localhost:4242
+ kill 898099
+ kill 898095
+ expected_nc_out='I
am
TELNET client'
+ fileEquals /tmp/nc.out 'I
am
TELNET client'
+ local fileData
++ cat /tmp/nc.out
+ fileData='I
am
TELNET client'
+ '[' 'I
am
TELNET client' = 'I
am
TELNET client' ']'
+ expected_telnet_out='Hello
From
NC'
+ fileEquals /tmp/telnet.out 'Hello
From
NC'
+ local fileData
++ cat /tmp/telnet.out
+ fileData='Hello
From
NC'
+ '[' 'Hello
From
NC' = 'Hello
From
NC' ']'
+ rm -f go-telnet
+ echo PASS
PASS
```

2024-01-18 19:49 UTC, ityulkanov commented on hw11_telnet_client/telnet.go
> +	conn, err := net.Dial("tcp", t.Address)
```suggestion
	conn, err := net.DiaTimeoutl("tcp", t.Address, t.Timeout)
```

2024-01-18 20:01 UTC, ityulkanov requested changes

2024-01-18 20:01 UTC, engineer-go commented on hw11_telnet_client/telnet.go
> +	conn, err := net.Dial("tcp", t.Address)
Пока не нахожу больших различий с работами которые тесты проходят, разве что вот это.

2024-01-18 20:01 UTC, engineer-go commented on hw11_telnet_client/telnet.go
> +	err := t.Conn.Close()
```suggestion
if t.Conn != nil {
	err := t.Conn.Close()
```

2024-01-18 20:01 UTC, engineer-go commented on hw11_telnet_client/telnet.go
> +
```suggestion
	}}

```

2024-01-18 20:01 UTC, ityulkanov commented on hw11_telnet_client/main.go
>  }
я бы еще порефакторил во эти методы. Тут как мне кажется много лишнего сейчас.

2024-01-20 07:26 UTC, Torchun commented
Правки сделал.
Внимательно посмотрел тесты, есть расхождения.

Локальные, которые поставляются с репой, содержат две проверки:
echo -e "Hello\nFrom\nNC\n"
echo -e "I\nam\nTELNET client\n"
Они успешно проходят локально и в github pipeline тоже

Но, в github pipeline есть третья проверка, которой нет локально:
https://github.com/Torchun/otus-go/actions/runs/7544571905/job/20538209910?pr=11#step:7:47
```
+ fileData='Hello
From
NC

EOF'
+ '[' 'Hello
From
NC

EOF' = 'Hello
From
NC' ']'
+ echo -e 'unexpected output, /tmp/telnet.out:\nHello
unexpected output, /tmp/telnet.out:
Hello
From
NC

EOF
From
NC

EOF'
```

Тут как будто есть третий тест со строкой
echo -e "Hello\nFrom\nNC\n\nEOF\n"
Но локально я такой вариант проверял, отрабатывает нормально:
```
+ expected_telnet_out='Hello
From
NC

EOF'
+ fileEquals /tmp/telnet.out 'Hello
From
NC

EOF'
+ local fileData
++ cat /tmp/telnet.out
+ fileData='Hello
From
NC

EOF'
+ '[' 'Hello
From
NC

EOF' = 'Hello
From
NC

EOF' ']'
+ rm -f go-telnet
+ echo PASS
PASS
```

Ощущение что где-то в тестах на гитхабе есть подводные камни.
И если честно, тесты данные локально и проверяемые при MR должны бы совпадать))

2024-01-22 11:42 UTC, ityulkanov approved these changes

2024-01-22 12:24 UTC, merged