Hw02 unpack string
Torchun/otus-go pull request #2
Opened 2023-10-23 20:33 UTC by Torchun

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-10-24 14:32 UTC, ityulkanov requested changes, later dismissed
Добрый день, Павел, рекомендую немного поправить логику и приму.

2023-10-24 14:32 UTC, engineer-go commented on hw02_unpack_string/unpack.go
> +			}
не рекомендую основывать логику на наличии или отсутствии ошибок. if err != уже устоявшаяся конструкция и я бы лично в продакшн коде подумал что вы тут ошибку обрабатываете... 
В общем лучше бы обработать ошибку как нужно, а return сделать после неё тогда уже.

2023-10-24 16:22 UTC, Torchun commented on hw02_unpack_string/unpack.go
> +			}
Действительно. Не знал об устоявшейся конструкции)) Поправил, получилось даже проще.

2023-10-25 14:56 UTC, ityulkanov requested changes, later dismissed

2023-10-25 14:56 UTC, ityulkanov commented on hw02_unpack_string/unpack.go
> +	result := ""
Вот это вот ошибка, пока принять не могу. Используя обычные строки мы резко вырастаем по использованию памяти. Для наших целей необходимо использовать strings.Builder, поправьте, пожалуйста.

2023-10-25 15:35 UTC, Torchun commented on hw02_unpack_string/unpack.go
> +	result := ""
Поправил, заодно везде на result.WriteString(...)

2023-10-26 08:31 UTC, ityulkanov commented on hw02_unpack_string/unpack.go
> +	result.WriteString("")
А зачем нужна вот эта строка?

2023-10-26 08:31 UTC, ityulkanov approved these changes

2023-10-26 10:29 UTC, Torchun commented on hw02_unpack_string/unpack.go
> +	result.WriteString("")
я не знаю zero value (вдруг там nil?) задаю пустую строку. Гугление почему-то мне не дало инфы.

2023-10-26 10:29 UTC, Torchun commented on hw02_unpack_string/unpack.go
> +	result.WriteString("")
только что понял что раз такой Write проходит, то и к zero value любой write пройдет)))
Похоже, строка лишняя. Убрать?

2023-10-26 11:27 UTC, merged